# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:52:23+00:00



import argparse
import json
import os
from typing import *
from typing import Any, Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Query
from pydantic import conint, constr

from models import (
    CitiesOrder,
    City,
    CountriesOrder,
    Country,
    DateFrom,
    DateFrom2,
    DateFrom3,
    DateTo,
    DateTo2,
    DateTo3,
    EntityTypes,
    HTTPValidationError,
    LastUpdatedFrom,
    LastUpdatedTo,
    Location,
    Location5,
    Location6,
    Location9,
    Location12,
    LocationsOrder,
    ManufacturerName,
    MeasOrder,
    ModelName,
    OpenAQCitiesResult,
    OpenAQCountriesResult,
    OpenAQParametersResult,
    OpenAQProjectsResult,
    OpenAQResult,
    OrderBy,
    Parameter,
    Parameter9,
    Parameter12,
    Project,
    ProjectsOrder,
    SensorTypes,
    Sort,
    SourceId,
    SourceName,
    SourceName4,
    SourceName5,
    SourceName9,
    SourceSlug,
    SourcesOrder,
    SourcesV1Order,
    Spatial,
    Temporal,
    TileJSON,
    Unit,
)

app = MCPProxy(
    description='API for OpenAQ LCS',
    title='OpenAQ',
    version='2.0.0',
    servers=[{'url': 'http://openaq.local'}],
)


@app.get('/favicon.ico', tags=['favicon_management'])
def favico_favicon_ico_get():
    """
    Favico
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/ping',
    description=""" Sanity check.
This will let the user know that the service is operational.
And this path operation will:
* show a lifesign """,
    tags=['ping_management'],
)
def pong_ping_get():
    """
    Pong
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/cities',
    tags=['city_data_handling', 'location_data_handling', 'country_data_handling'],
)
def cities_getv1_v1_cities_get(
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'asc',
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    city: Optional[City] = None,
    order_by: Optional[CitiesOrder] = 'city',
    entity: Optional[str] = None,
):
    """
    Provides a simple listing of cities within the platform
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/countries', tags=['country_data_handling', 'latest_data_fetching'])
def countries_getv1_v1_countries_get(
    limit: Optional[int] = 200,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'asc',
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    order_by: Optional[CountriesOrder] = 'country',
):
    """
    Countries Getv1
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/countries/{country_id}',
    tags=['country_data_handling', 'location_data_handling', 'latest_data_fetching'],
)
def countries_get_v1_countries__country_id__get(
    country_id: constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2),
    limit: Optional[int] = 200,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'asc',
    country: Optional[Country] = None,
    order_by: Optional[CountriesOrder] = 'country',
):
    """
    Countries Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/latest',
    tags=[
        'latest_data_fetching',
        'location_data_handling',
        'city_data_handling',
        'country_data_handling',
        'parameter_fetching',
        'source_information_retrieval',
    ],
)
def latest_v1_get_v1_latest_get(
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'desc',
    has_geo: Optional[bool] = None,
    parameter_id: Optional[int] = None,
    parameter: Optional[Parameter] = None,
    unit: Optional[Unit] = None,
    coordinates: Optional[
        constr(pattern=r'^-?\d{1,2}\.?\d{0,8},-?1?\d{1,2}\.?\d{0,8}$')
    ] = None,
    radius: Optional[conint(le=100000, gt=0)] = 1000,
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    city: Optional[City] = None,
    location_id: Optional[int] = None,
    location: Optional[Location] = None,
    order_by: Optional[LocationsOrder] = 'lastUpdated',
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
    source_name: Optional[SourceName] = Query(None, alias='sourceName'),
    entity: Optional[EntityTypes] = None,
    sensor_type: Optional[SensorTypes] = Query(None, alias='sensorType'),
    model_name: Optional[ModelName] = Query(None, alias='modelName'),
    manufacturer_name: Optional[ManufacturerName] = Query(
        None, alias='manufacturerName'
    ),
    dump_raw: Optional[bool] = Query(False, alias='dumpRaw'),
):
    """
    Latest V1 Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/latest/{location_id}',
    tags=[
        'latest_data_fetching',
        'location_data_handling',
        'city_data_handling',
        'country_data_handling',
        'parameter_fetching',
    ],
)
def latest_v1_get_v1_latest__location_id__get(
    location_id: int,
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'desc',
    has_geo: Optional[bool] = None,
    parameter_id: Optional[int] = None,
    parameter: Optional[Parameter] = None,
    unit: Optional[Unit] = None,
    coordinates: Optional[
        constr(pattern=r'^-?\d{1,2}\.?\d{0,8},-?1?\d{1,2}\.?\d{0,8}$')
    ] = None,
    radius: Optional[conint(le=100000, gt=0)] = 1000,
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    city: Optional[City] = None,
    location: Optional[Location] = None,
    order_by: Optional[LocationsOrder] = 'lastUpdated',
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
    source_name: Optional[SourceName] = Query(None, alias='sourceName'),
    entity: Optional[EntityTypes] = None,
    sensor_type: Optional[SensorTypes] = Query(None, alias='sensorType'),
    model_name: Optional[ModelName] = Query(None, alias='modelName'),
    manufacturer_name: Optional[ManufacturerName] = Query(
        None, alias='manufacturerName'
    ),
    dump_raw: Optional[bool] = Query(False, alias='dumpRaw'),
):
    """
    Latest V1 Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/locations',
    tags=[
        'city_data_handling',
        'country_data_handling',
        'location_data_handling',
        'latest_data_fetching',
        'data_source_management',
        'parameter_fetching',
    ],
)
def locationsv1_get_v1_locations_get(
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'desc',
    has_geo: Optional[bool] = None,
    parameter_id: Optional[int] = None,
    parameter: Optional[Parameter] = None,
    unit: Optional[Unit] = None,
    coordinates: Optional[
        constr(pattern=r'^-?\d{1,2}\.?\d{0,8},-?1?\d{1,2}\.?\d{0,8}$')
    ] = None,
    radius: Optional[conint(le=100000, gt=0)] = 1000,
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    city: Optional[City] = None,
    location_id: Optional[int] = None,
    location: Optional[Location] = None,
    order_by: Optional[LocationsOrder] = 'lastUpdated',
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
    source_name: Optional[SourceName] = Query(None, alias='sourceName'),
    entity: Optional[EntityTypes] = None,
    sensor_type: Optional[SensorTypes] = Query(None, alias='sensorType'),
    model_name: Optional[ModelName] = Query(None, alias='modelName'),
    manufacturer_name: Optional[ManufacturerName] = Query(
        None, alias='manufacturerName'
    ),
    dump_raw: Optional[bool] = Query(False, alias='dumpRaw'),
):
    """
    Locationsv1 Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/locations/{location_id}',
    tags=[
        'location_data_handling',
        'city_data_handling',
        'country_data_handling',
        'latest_data_fetching',
        'parameter_fetching',
    ],
)
def locationsv1_get_v1_locations__location_id__get(
    location_id: int,
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'desc',
    has_geo: Optional[bool] = None,
    parameter_id: Optional[int] = None,
    parameter: Optional[Parameter] = None,
    unit: Optional[Unit] = None,
    coordinates: Optional[
        constr(pattern=r'^-?\d{1,2}\.?\d{0,8},-?1?\d{1,2}\.?\d{0,8}$')
    ] = None,
    radius: Optional[conint(le=100000, gt=0)] = 1000,
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    city: Optional[City] = None,
    location: Optional[Location] = None,
    order_by: Optional[LocationsOrder] = 'lastUpdated',
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
    source_name: Optional[SourceName] = Query(None, alias='sourceName'),
    entity: Optional[EntityTypes] = None,
    sensor_type: Optional[SensorTypes] = Query(None, alias='sensorType'),
    model_name: Optional[ModelName] = Query(None, alias='modelName'),
    manufacturer_name: Optional[ManufacturerName] = Query(
        None, alias='manufacturerName'
    ),
    dump_raw: Optional[bool] = Query(False, alias='dumpRaw'),
):
    """
    Locationsv1 Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/measurements',
    tags=[
        'measurement_data_management',
        'latest_data_fetching',
        'country_data_handling',
        'location_data_handling',
        'parameter_fetching',
    ],
)
def measurements_get_v1_v1_measurements_get(
    format: Optional[str] = None,
    date_from: Optional[DateFrom] = '2000-01-01T00:00:00+00:00',
    date_to: Optional[DateTo] = '2021-08-23T09:48:00+00:00',
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'desc',
    has_geo: Optional[bool] = None,
    parameter_id: Optional[int] = None,
    parameter: Optional[Parameter] = None,
    unit: Optional[Unit] = None,
    coordinates: Optional[
        constr(pattern=r'^-?\d{1,2}\.?\d{0,8},-?1?\d{1,2}\.?\d{0,8}$')
    ] = None,
    radius: Optional[conint(le=100000, gt=0)] = 1000,
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    city: Optional[City] = None,
    location_id: Optional[int] = None,
    location: Optional[Location] = None,
    order_by: Optional[MeasOrder] = 'datetime',
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
    project: Optional[int] = None,
    entity: Optional[EntityTypes] = None,
    sensor_type: Optional[SensorTypes] = Query(None, alias='sensorType'),
    value_from: Optional[float] = None,
    value_to: Optional[float] = None,
    include_fields: Optional[str] = None,
):
    """
    Measurements Get V1
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/parameters',
    tags=['latest_data_fetching', 'data_source_management', 'parameter_fetching'],
)
def parameters_getv1_v1_parameters_get(
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'asc',
    source_name: Optional[SourceName4] = Query(None, alias='sourceName'),
    source_id: Optional[SourceId] = Query(None, alias='sourceId'),
    source_slug: Optional[SourceSlug] = Query(None, alias='sourceSlug'),
    order_by: Optional[OrderBy] = 'id',
):
    """
    Parameters Getv1
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/sources',
    tags=[
        'latest_data_fetching',
        'data_source_management',
        'source_information_retrieval',
    ],
)
def sources_v1_get_v1_sources_get(
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'asc',
    name: Optional[str] = None,
    order_by: Optional[SourcesV1Order] = 'name',
):
    """
    Sources V1 Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/averages',
    tags=[
        'average_value_computation',
        'parameter_fetching',
        'project_information_retrieval',
        'country_data_handling',
        'measurement_data_management',
    ],
)
def averages_v2_get_v2_averages_get(
    date_from: Optional[DateFrom] = '2000-01-01T00:00:00+00:00',
    date_to: Optional[DateTo] = '2021-08-23T09:48:00+00:00',
    parameter_id: Optional[int] = None,
    parameter: Optional[Parameter] = None,
    unit: Optional[Unit] = None,
    project_id: Optional[int] = None,
    project: Optional[Project] = None,
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'desc',
    spatial: Spatial = ...,
    temporal: Temporal = ...,
    location: Optional[Location5] = None,
    group: Optional[bool] = False,
):
    """
    Averages V2 Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/cities',
    tags=['city_data_handling', 'location_data_handling', 'country_data_handling'],
)
def cities_get_v2_cities_get(
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'asc',
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    city: Optional[City] = None,
    order_by: Optional[CitiesOrder] = 'city',
    entity: Optional[str] = None,
):
    """
    Provides a simple listing of cities within the platform
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/countries',
    tags=['country_data_handling', 'latest_data_fetching', 'location_data_handling'],
)
def countries_get_v2_countries_get(
    limit: Optional[int] = 200,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'asc',
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    order_by: Optional[CountriesOrder] = 'country',
):
    """
    Countries Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/countries/{country_id}',
    tags=['country_data_handling', 'location_data_handling', 'latest_data_fetching'],
)
def countries_get_v2_countries__country_id__get(
    country_id: constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2),
    limit: Optional[int] = 200,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'asc',
    country: Optional[Country] = None,
    order_by: Optional[CountriesOrder] = 'country',
):
    """
    Countries Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/latest',
    tags=[
        'latest_data_fetching',
        'location_data_handling',
        'country_data_handling',
        'city_data_handling',
        'parameter_fetching',
        'data_source_management',
    ],
)
def latest_get_v2_latest_get(
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'desc',
    has_geo: Optional[bool] = None,
    parameter_id: Optional[int] = None,
    parameter: Optional[Parameter] = None,
    unit: Optional[Unit] = None,
    coordinates: Optional[
        constr(pattern=r'^-?\d{1,2}\.?\d{0,8},-?1?\d{1,2}\.?\d{0,8}$')
    ] = None,
    radius: Optional[conint(le=100000, gt=0)] = 1000,
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    city: Optional[City] = None,
    location_id: Optional[int] = None,
    location: Optional[Location6] = None,
    order_by: Optional[LocationsOrder] = 'lastUpdated',
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
    source_name: Optional[SourceName5] = Query(None, alias='sourceName'),
    entity: Optional[EntityTypes] = None,
    sensor_type: Optional[SensorTypes] = Query(None, alias='sensorType'),
    model_name: Optional[ModelName] = Query(None, alias='modelName'),
    manufacturer_name: Optional[ManufacturerName] = Query(
        None, alias='manufacturerName'
    ),
    dump_raw: Optional[bool] = Query(False, alias='dumpRaw'),
):
    """
    Latest Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/latest/{location_id}',
    tags=[
        'latest_data_fetching',
        'location_data_handling',
        'city_data_handling',
        'country_data_handling',
        'parameter_fetching',
    ],
)
def latest_get_v2_latest__location_id__get(
    location_id: int,
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'desc',
    has_geo: Optional[bool] = None,
    parameter_id: Optional[int] = None,
    parameter: Optional[Parameter] = None,
    unit: Optional[Unit] = None,
    coordinates: Optional[
        constr(pattern=r'^-?\d{1,2}\.?\d{0,8},-?1?\d{1,2}\.?\d{0,8}$')
    ] = None,
    radius: Optional[conint(le=100000, gt=0)] = 1000,
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    city: Optional[City] = None,
    location: Optional[Location6] = None,
    order_by: Optional[LocationsOrder] = 'lastUpdated',
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
    source_name: Optional[SourceName5] = Query(None, alias='sourceName'),
    entity: Optional[EntityTypes] = None,
    sensor_type: Optional[SensorTypes] = Query(None, alias='sensorType'),
    model_name: Optional[ModelName] = Query(None, alias='modelName'),
    manufacturer_name: Optional[ManufacturerName] = Query(
        None, alias='manufacturerName'
    ),
    dump_raw: Optional[bool] = Query(False, alias='dumpRaw'),
):
    """
    Latest Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/locations',
    tags=[
        'location_data_handling',
        'city_data_handling',
        'country_data_handling',
        'latest_data_fetching',
        'parameter_fetching',
    ],
)
def locations_get_v2_locations_get(
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'desc',
    has_geo: Optional[bool] = None,
    parameter_id: Optional[int] = None,
    parameter: Optional[Parameter] = None,
    unit: Optional[Unit] = None,
    coordinates: Optional[
        constr(pattern=r'^-?\d{1,2}\.?\d{0,8},-?1?\d{1,2}\.?\d{0,8}$')
    ] = None,
    radius: Optional[conint(le=100000, gt=0)] = 1000,
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    city: Optional[City] = None,
    location_id: Optional[int] = None,
    location: Optional[Location6] = None,
    order_by: Optional[LocationsOrder] = 'lastUpdated',
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
    source_name: Optional[SourceName5] = Query(None, alias='sourceName'),
    entity: Optional[EntityTypes] = None,
    sensor_type: Optional[SensorTypes] = Query(None, alias='sensorType'),
    model_name: Optional[ModelName] = Query(None, alias='modelName'),
    manufacturer_name: Optional[ManufacturerName] = Query(
        None, alias='manufacturerName'
    ),
    dump_raw: Optional[bool] = Query(False, alias='dumpRaw'),
):
    """
    Locations Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/locations/tiles/mobile-generalized/tiles.json',
    tags=['mobile_data_operations', 'location_data_handling'],
)
def mobilegentilejson_summary():
    """
    Mobilegentilejson
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/locations/tiles/mobile-generalized/{z}/{x}/{y}.pbf',
    tags=['mobile_data_operations', 'latest_data_fetching', 'location_data_handling'],
)
def get_mobilegentile_locations(
    z: int,
    x: int = ...,
    y: int = ...,
    parameter: Optional[Parameter9] = None,
    location: Optional[Location9] = None,
    last_updated_from: Optional[LastUpdatedFrom] = Query(None, alias='lastUpdatedFrom'),
    last_updated_to: Optional[LastUpdatedTo] = Query(None, alias='lastUpdatedTo'),
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    project: Optional[int] = None,
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
):
    """
    Get Mobilegentile
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/locations/tiles/mobile/tiles.json',
    tags=['mobile_data_operations', 'map_tile_management'],
)
def mobiletilejson_v2_locations_tiles_mobile_tiles_json_get():
    """
    Mobiletilejson
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/locations/tiles/mobile/{z}/{x}/{y}.pbf',
    tags=[
        'mobile_data_operations',
        'map_tile_management',
        'latest_data_fetching',
        'location_data_handling',
    ],
)
def get_mobiletile_v2_locations_tiles_mobile__z___x___y__pbf_get(
    z: int,
    x: int = ...,
    y: int = ...,
    date_from: DateFrom2 = Query(..., alias='dateFrom'),
    date_to: DateTo2 = Query(..., alias='dateTo'),
    parameter: Optional[Parameter9] = None,
    location: Optional[Location9] = None,
    last_updated_from: Optional[LastUpdatedFrom] = Query(None, alias='lastUpdatedFrom'),
    last_updated_to: Optional[LastUpdatedTo] = Query(None, alias='lastUpdatedTo'),
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    project: Optional[int] = None,
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
):
    """
    Get Mobiletile
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/locations/tiles/tiles.json',
    tags=['map_tile_management', 'location_data_handling', 'data_source_management'],
)
def tilejson_v2_locations_tiles_tiles_json_get():
    """
    Tilejson
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v2/locations/tiles/viewer', tags=['summary_information_retrieval'])
def demo_v2_locations_tiles_viewer_get():
    """
    Demo
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/locations/tiles/{z}/{x}/{y}.pbf',
    tags=[
        'map_tile_management',
        'location_data_handling',
        'latest_data_fetching',
        'mobile_data_operations',
    ],
)
def get_tile_v2_locations_tiles__z___x___y__pbf_get(
    z: int,
    x: int = ...,
    y: int = ...,
    parameter: Optional[Parameter9] = None,
    location: Optional[Location9] = None,
    last_updated_from: Optional[LastUpdatedFrom] = Query(None, alias='lastUpdatedFrom'),
    last_updated_to: Optional[LastUpdatedTo] = Query(None, alias='lastUpdatedTo'),
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    project: Optional[int] = None,
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
):
    """
    Get Tile
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/locations/{location_id}',
    tags=[
        'location_data_handling',
        'city_data_handling',
        'country_data_handling',
        'latest_data_fetching',
        'parameter_fetching',
    ],
)
def locations_get_v2_locations__location_id__get(
    location_id: int,
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'desc',
    has_geo: Optional[bool] = None,
    parameter_id: Optional[int] = None,
    parameter: Optional[Parameter12] = None,
    unit: Optional[Unit] = None,
    coordinates: Optional[
        constr(pattern=r'^-?\d{1,2}\.?\d{0,8},-?1?\d{1,2}\.?\d{0,8}$')
    ] = None,
    radius: Optional[conint(le=100000, gt=0)] = 1000,
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    city: Optional[City] = None,
    location: Optional[Location12] = None,
    order_by: Optional[LocationsOrder] = 'lastUpdated',
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
    source_name: Optional[SourceName5] = Query(None, alias='sourceName'),
    entity: Optional[EntityTypes] = None,
    sensor_type: Optional[SensorTypes] = Query(None, alias='sensorType'),
    model_name: Optional[ModelName] = Query(None, alias='modelName'),
    manufacturer_name: Optional[ManufacturerName] = Query(
        None, alias='manufacturerName'
    ),
    dump_raw: Optional[bool] = Query(False, alias='dumpRaw'),
):
    """
    Locations Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/manufacturers',
    tags=[
        'manufacturer_info_management',
        'data_source_management',
        'latest_data_fetching',
    ],
)
def mfr_get_v2_manufacturers_get():
    """
    Mfr Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/measurements',
    tags=[
        'measurement_data_management',
        'latest_data_fetching',
        'location_data_handling',
        'parameter_fetching',
    ],
)
def measurements_get_v2_measurements_get(
    format: Optional[str] = None,
    date_from: Optional[DateFrom3] = '2000-01-01T00:00:00+00:00',
    date_to: Optional[DateTo3] = '2021-08-23T09:48:00+00:00',
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'desc',
    has_geo: Optional[bool] = None,
    parameter_id: Optional[int] = None,
    parameter: Optional[Parameter12] = None,
    unit: Optional[Unit] = None,
    coordinates: Optional[
        constr(pattern=r'^-?\d{1,2}\.?\d{0,8},-?1?\d{1,2}\.?\d{0,8}$')
    ] = None,
    radius: Optional[conint(le=100000, gt=0)] = 1000,
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    city: Optional[City] = None,
    location_id: Optional[int] = None,
    location: Optional[Location12] = None,
    order_by: Optional[MeasOrder] = 'datetime',
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
    project: Optional[int] = None,
    entity: Optional[EntityTypes] = None,
    sensor_type: Optional[SensorTypes] = Query(None, alias='sensorType'),
    value_from: Optional[float] = None,
    value_to: Optional[float] = None,
    include_fields: Optional[str] = None,
):
    """
    Measurements Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v2/models', tags=['model_information_management'])
def model_get_v2_models_get():
    """
    Model Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/parameters',
    tags=[
        'latest_data_fetching',
        'data_source_management',
        'parameter_fetching',
        'source_information_retrieval',
    ],
)
def parameters_get_v2_parameters_get(
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'asc',
    source_name: Optional[SourceName9] = Query(None, alias='sourceName'),
    source_id: Optional[SourceId] = Query(None, alias='sourceId'),
    source_slug: Optional[SourceSlug] = Query(None, alias='sourceSlug'),
    order_by: Optional[OrderBy] = 'id',
):
    """
    Parameters Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/projects',
    tags=[
        'project_information_retrieval',
        'latest_data_fetching',
        'parameter_fetching',
        'location_data_handling',
    ],
)
def projects_get_v2_projects_get(
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'asc',
    parameter_id: Optional[int] = None,
    parameter: Optional[Parameter12] = None,
    unit: Optional[Unit] = None,
    project_id: Optional[int] = None,
    project: Optional[Project] = None,
    order_by: Optional[ProjectsOrder] = 'lastUpdated',
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
    entity: Optional[str] = None,
    sensor_type: Optional[str] = Query(None, alias='sensorType'),
    source_name: Optional[SourceName9] = Query(None, alias='sourceName'),
):
    """
    Projects Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/projects/{project_id}',
    tags=[
        'project_information_retrieval',
        'data_source_management',
        'latest_data_fetching',
    ],
)
def projects_get_v2_projects__project_id__get(
    project_id: int,
    country_id: Optional[
        constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)
    ] = None,
    country: Optional[Country] = None,
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'asc',
    parameter_id: Optional[int] = None,
    parameter: Optional[Parameter12] = None,
    unit: Optional[Unit] = None,
    project: Optional[Project] = None,
    order_by: Optional[ProjectsOrder] = 'lastUpdated',
    is_mobile: Optional[bool] = Query(None, alias='isMobile'),
    is_analysis: Optional[bool] = Query(None, alias='isAnalysis'),
    entity: Optional[str] = None,
    sensor_type: Optional[str] = Query(None, alias='sensorType'),
    source_name: Optional[SourceName9] = Query(None, alias='sourceName'),
):
    """
    Projects Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/sources',
    tags=[
        'latest_data_fetching',
        'data_source_management',
        'source_information_retrieval',
    ],
)
def sources_get_v2_sources_get(
    limit: Optional[conint(le=100000, gt=0)] = 100,
    page: Optional[conint(le=6000, gt=0)] = 1,
    offset: Optional[conint(ge=0, le=10000)] = 0,
    sort: Optional[Sort] = 'asc',
    source_name: Optional[SourceName9] = Query(None, alias='sourceName'),
    source_id: Optional[SourceId] = Query(None, alias='sourceId'),
    source_slug: Optional[SourceSlug] = Query(None, alias='sourceSlug'),
    order_by: Optional[SourcesOrder] = 'sourceName',
):
    """
    Sources Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v2/sources/readme/{slug}', tags=['readme_file_retrieval'])
def readme_get_v2_sources_readme__slug__get(slug: str):
    """
    Readme Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v2/summary', tags=['summary_information_retrieval'])
def summary_get_v2_summary_get():
    """
    Summary Get
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
