# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:52:23+00:00

from __future__ import annotations

from datetime import date
from datetime import datetime as datetime_aliased
from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field, RootModel, conint, constr


class CitiesOrder(Enum):
    city = 'city'
    country = 'country'
    firstUpdated = 'firstUpdated'
    lastUpdated = 'lastUpdated'


class CitiesRow(BaseModel):
    city: str = Field(..., title='City')
    count: int = Field(..., title='Count')
    country: Optional[str] = Field(None, title='Country')
    firstUpdated: datetime_aliased = Field(..., title='Firstupdated')
    lastUpdated: datetime_aliased = Field(..., title='Lastupdated')
    locations: int = Field(..., title='Locations')
    parameters: List[str] = Field(..., title='Parameters')


class CountriesOrder(Enum):
    country = 'country'
    firstUpdated = 'firstUpdated'
    lastUpdated = 'lastUpdated'
    locations = 'locations'
    count = 'count'


class CountriesRow(BaseModel):
    cities: int = Field(..., title='Cities')
    code: str = Field(..., title='Code')
    count: int = Field(..., title='Count')
    firstUpdated: datetime_aliased = Field(..., title='Firstupdated')
    lastUpdated: datetime_aliased = Field(..., title='Lastupdated')
    locations: int = Field(..., title='Locations')
    name: str = Field(..., title='Name')
    parameters: List[str] = Field(..., title='Parameters')
    sources: int = Field(..., title='Sources')


class EntityTypes(Enum):
    government = 'government'
    community = 'community'
    research = 'research'


class LocationsOrder(Enum):
    city = 'city'
    country = 'country'
    location = 'location'
    sourceName = 'sourceName'
    firstUpdated = 'firstUpdated'
    lastUpdated = 'lastUpdated'
    count = 'count'
    random = 'random'


class MeasOrder(Enum):
    city = 'city'
    country = 'country'
    location = 'location'
    datetime = 'datetime'


class Meta(BaseModel):
    found: Optional[int] = Field(0, title='Found')
    license: Optional[str] = Field('CC BY 4.0d', title='License')
    limit: Optional[int] = Field(100, title='Limit')
    name: Optional[str] = Field('openaq-api', title='Name')
    page: Optional[int] = Field(1, title='Page')
    website: Optional[str] = Field('/', title='Website')


class OpenAQCitiesResult(BaseModel):
    meta: Optional[Meta] = Field(
        default_factory=lambda: Meta.model_validate(
            {
                'found': 0,
                'license': 'CC BY 4.0d',
                'limit': 100,
                'name': 'openaq-api',
                'page': 1,
                'website': '/',
            }
        ),
        title='Meta',
    )
    results: List[CitiesRow] = Field(..., title='Results')


class OpenAQCountriesResult(BaseModel):
    meta: Optional[Meta] = Field(
        default_factory=lambda: Meta.model_validate(
            {
                'found': 0,
                'license': 'CC BY 4.0d',
                'limit': 100,
                'name': 'openaq-api',
                'page': 1,
                'website': '/',
            }
        ),
        title='Meta',
    )
    results: List[CountriesRow] = Field(..., title='Results')


class OpenAQResult(BaseModel):
    meta: Optional[Meta] = Field(
        default_factory=lambda: Meta.model_validate(
            {
                'found': 0,
                'license': 'CC BY 4.0d',
                'limit': 100,
                'name': 'openaq-api',
                'page': 1,
                'website': '/',
            }
        ),
        title='Meta',
    )
    results: Optional[List] = Field([], title='Results')


class ParametersRow(BaseModel):
    description: str = Field(..., title='Description')
    displayName: str = Field(..., title='Displayname')
    id: int = Field(..., title='Id')
    isCore: Optional[bool] = Field(None, title='Iscore')
    maxColorValue: Optional[float] = Field(None, title='Maxcolorvalue')
    name: str = Field(..., title='Name')
    preferredUnit: str = Field(..., title='Preferredunit')


class ProjectParameterDetails(BaseModel):
    average: float = Field(..., title='Average')
    count: int = Field(..., title='Count')
    displayName: Optional[str] = Field(None, title='Displayname')
    firstUpdated: datetime_aliased = Field(..., title='Firstupdated')
    lastUpdated: datetime_aliased = Field(..., title='Lastupdated')
    lastValue: float = Field(..., title='Lastvalue')
    locations: int = Field(..., title='Locations')
    parameter: str = Field(..., title='Parameter')
    parameterId: int = Field(..., title='Parameterid')
    unit: str = Field(..., title='Unit')


class ProjectsOrder(Enum):
    id = 'id'
    name = 'name'
    subtitle = 'subtitle'
    firstUpdated = 'firstUpdated'
    lastUpdated = 'lastUpdated'


class ProjectsRow(BaseModel):
    bbox: Optional[List[float]] = Field(None, title='Bbox')
    countries: Optional[List[str]] = Field(None, title='Countries')
    entity: Optional[str] = Field(None, title='Entity')
    firstUpdated: datetime_aliased = Field(..., title='Firstupdated')
    id: int = Field(..., title='Id')
    isAnalysis: Optional[bool] = Field(None, title='Isanalysis')
    isMobile: Optional[bool] = Field(None, title='Ismobile')
    lastUpdated: datetime_aliased = Field(..., title='Lastupdated')
    locationIds: List[int] = Field(..., title='Locationids')
    locations: int = Field(..., title='Locations')
    measurements: int = Field(..., title='Measurements')
    name: str = Field(..., title='Name')
    parameters: List[ProjectParameterDetails] = Field(..., title='Parameters')
    sensorType: Optional[str] = Field(None, title='Sensortype')
    sources: Optional[List] = Field(None, title='Sources')
    subtitle: str = Field(..., title='Subtitle')


class SensorTypes(Enum):
    reference_grade = 'reference grade'
    low_cost_sensor = 'low-cost sensor'


class Sort(Enum):
    asc = 'asc'
    desc = 'desc'


class SourcesOrder(Enum):
    sourceName = 'sourceName'
    firstUpdated = 'firstUpdated'
    lastUpdated = 'lastUpdated'


class SourcesV1Order(Enum):
    name = 'name'


class Spatial(Enum):
    country = 'country'
    location = 'location'
    project = 'project'
    total = 'total'


class Temporal(Enum):
    day = 'day'
    month = 'month'
    year = 'year'
    moy = 'moy'
    dow = 'dow'
    hour = 'hour'
    hod = 'hod'


class TileJSON(BaseModel):
    attribution: Optional[str] = Field(None, title='Attribution')
    bounds: Optional[List[float]] = Field([-180, -90, 180, 90], title='Bounds')
    data: Optional[List[str]] = Field([], title='Data')
    description: Optional[str] = Field(None, title='Description')
    grids: Optional[List[str]] = Field([], title='Grids')
    legend: Optional[str] = Field(None, title='Legend')
    maxzoom: Optional[conint(ge=0, le=30)] = Field(30, title='Maxzoom')
    minzoom: Optional[conint(ge=0, le=30)] = Field(0, title='Minzoom')
    name: Optional[str] = Field(None, title='Name')
    scheme: Optional[str] = Field('xyz', title='Scheme')
    template: Optional[str] = Field(None, title='Template')
    tilejson: Optional[str] = Field('2.2.0', title='Tilejson')
    tiles: List[str] = Field(..., title='Tiles')
    version: Optional[str] = Field('1.0.0', title='Version')


class ValidationError(BaseModel):
    loc: List[str] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class Country(
    RootModel[List[constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)]]
):
    root: List[constr(pattern=r'[a-zA-Z][a-zA-Z]', min_length=2, max_length=2)] = Field(
        ...,
        description='\n        Limit results by a certain country using two letter country code.\n        (ex. ?country=US or ?country=US&country=MX)\n        ',
        title='Country',
    )


class City(RootModel[List[str]]):
    root: List[str] = Field(
        ...,
        description='\n        Limit results by a certain city or cities.\n        (ex. ?city=Chicago or ?city=Chicago&city=Boston)\n        ',
        title='City',
    )


class Parameter(RootModel[List[Union[conint(le=2147483647, gt=0), str]]]):
    root: List[Union[conint(le=2147483647, gt=0), str]] = Field(..., title='Parameter')


class Unit(RootModel[List[str]]):
    root: List[str] = Field(..., title='Unit')


class Location(RootModel[List[Union[int, str]]]):
    root: List[Union[int, str]] = Field(..., title='Location')


class SourceName(RootModel[List[str]]):
    root: List[str] = Field(
        ..., description='Name of the data source', title='Sourcename'
    )


class ModelName(RootModel[List[str]]):
    root: List[str] = Field(..., description='Model Name of Sensor', title='Modelname')


class ManufacturerName(RootModel[List[str]]):
    root: List[str] = Field(
        ..., description='Manufacturer of Sensor', title='Manufacturername'
    )


class DateFrom(RootModel[Union[datetime_aliased, date]]):
    root: Union[datetime_aliased, date] = Field(..., title='Date From')


class DateTo(RootModel[Union[datetime_aliased, date]]):
    root: Union[datetime_aliased, date] = Field(..., title='Date To')


class SourceName4(RootModel[List[str]]):
    root: List[str] = Field(..., title='Sourcename')


class SourceId(RootModel[List[int]]):
    root: List[int] = Field(..., title='Sourceid')


class SourceSlug(RootModel[List[str]]):
    root: List[str] = Field(..., title='Sourceslug')


class OrderBy(RootModel[str]):
    root: str = Field(..., title='Order By')


class Project(RootModel[List[Union[conint(le=2147483647, gt=0), str]]]):
    root: List[Union[conint(le=2147483647, gt=0), str]] = Field(..., title='Project')


class Location5(RootModel[List[str]]):
    root: List[str] = Field(..., title='Location')


class Location6(RootModel[List[Union[int, str]]]):
    root: List[Union[int, str]] = Field(..., title='Location')


class SourceName5(RootModel[List[str]]):
    root: List[str] = Field(
        ..., description='Name of the data source', title='Sourcename'
    )


class Parameter9(RootModel[Union[int, str]]):
    root: Union[int, str] = Field(..., title='Parameter')


class Location9(RootModel[List[int]]):
    root: List[int] = Field(
        ..., description='limit data to location id', title='Location'
    )


class LastUpdatedFrom(RootModel[Union[datetime_aliased, date]]):
    root: Union[datetime_aliased, date] = Field(..., title='Lastupdatedfrom')


class LastUpdatedTo(RootModel[Union[datetime_aliased, date]]):
    root: Union[datetime_aliased, date] = Field(..., title='Lastupdatedto')


class DateFrom2(RootModel[Union[datetime_aliased, date]]):
    root: Union[datetime_aliased, date] = Field(..., title='Datefrom')


class DateTo2(RootModel[Union[datetime_aliased, date]]):
    root: Union[datetime_aliased, date] = Field(..., title='Dateto')


class Parameter12(RootModel[List[Union[conint(le=2147483647, gt=0), str]]]):
    root: List[Union[conint(le=2147483647, gt=0), str]] = Field(..., title='Parameter')


class Location12(RootModel[List[Union[int, str]]]):
    root: List[Union[int, str]] = Field(..., title='Location')


class DateFrom3(RootModel[Union[datetime_aliased, date]]):
    root: Union[datetime_aliased, date] = Field(..., title='Date From')


class DateTo3(RootModel[Union[datetime_aliased, date]]):
    root: Union[datetime_aliased, date] = Field(..., title='Date To')


class SourceName9(RootModel[List[str]]):
    root: List[str] = Field(..., title='Sourcename')


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')


class OpenAQParametersResult(BaseModel):
    meta: Optional[Meta] = Field(
        default_factory=lambda: Meta.model_validate(
            {
                'found': 0,
                'license': 'CC BY 4.0d',
                'limit': 100,
                'name': 'openaq-api',
                'page': 1,
                'website': '/',
            }
        ),
        title='Meta',
    )
    results: List[ParametersRow] = Field(..., title='Results')


class OpenAQProjectsResult(BaseModel):
    meta: Optional[Meta] = Field(
        default_factory=lambda: Meta.model_validate(
            {
                'found': 0,
                'license': 'CC BY 4.0d',
                'limit': 100,
                'name': 'openaq-api',
                'page': 1,
                'website': '/',
            }
        ),
        title='Meta',
    )
    results: List[ProjectsRow] = Field(..., title='Results')
